spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Yi920517.
#    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: com.app.medel
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path:
    session:
      timeout: 1800
    encoding:
      enabled: true
      charset: UTF-8
      force: true

wxpay:
  appid: wx67c9da8404589ae3
  mch_id: 1230000109
  key: wx67c9da8404589ae3



